version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/docker-run.sh
      timeout: 300
      runas: ec2-user
