version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/docker-run.sh
      timeout: 300
      runas: root
